---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: capcal-bookkeeper
spec:
  replicas: 2
  selector:
    matchLabels:
      name: capcal-bookkeeper
  template:
    metadata:
      labels:
        name: capcal-bookkeeper
    spec:
      containers:
        - name: capcal-bookkeeper
          image: bttf/capcal-bookkeeper:$COMMIT_SHA1
          imagePullPolicy: Always
          ports:
            - containerPort: 3001
          env:
            - name: NODE_ENV
              value: production
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: capcal-secrets
                  key: REDIS_HOST
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: capcal-secrets
                  key: REDIS_PASSWORD
            - name: RPC_HOST
              valueFrom:
                secretKeyRef:
                  name: capcal-secrets
                  key: RPC_HOST
            - name: RPC_PORT
              valueFrom:
                secretKeyRef:
                  name: capcal-secrets
                  key: RPC_PORT
            - name: RPC_SECRET
              valueFrom:
                secretKeyRef:
                  name: capcal-secrets
                  key: RPC_SECRET
      imagePullSecrets:
        - name: regcred
