version: '3'
services:
  api:
    build: api
    command: yarn dev
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - ./api:/user/src/app
      - /user/src/app/node_modules
    depends_on:
      - db
    environment:
      PORT: 3000
      PGHOST: db
      PGUSER: postgres
      PGDATABASE: capital-calendar-dev
      PGPASSWORD:
      PGPORT: "5432"
      AUTH_SECRET: "m0n4l!s4"
      GOOGLE_CLIENT_ID: "$CAPCAL_GOOGLE_CLIENT_ID"
      GOOGLE_CLIENT_SECRET: "$CAPCAL_GOOGLE_CLIENT_SECRET"
      GOOGLE_CALLBACK_URL: "http://localhost:8080/google"
      PLAID_CLIENT_ID: "$CAPCAL_PLAID_CLIENT_ID"
      PLAID_SECRET: "$CAPCAL_PLAID_SECRET"
      PLAID_PUBLIC_KEY: "$CAPCAL_PLAID_PUBLIC_KEY"
      PLAID_PRODUCTS: "$CAPCAL_PLAID_PRODUCTS"
      PLAID_ENV: "$CAPCAL_PLAID_ENV"
      RPC_SECRET: "coltr4n3"
  plaid-bookkeeper:
    build: plaid-bookkeeper
    command: yarn dev
    ports:
      - '3001:3001'
      - '9230:9230'
    volumes:
      - ./plaid-bookkeeper:/user/src/app
      - /user/src/app/node_modules
    environment:
      PORT: 3001
      REDIS_HOST: redis
      RPC_HOST: api
      RPC_PORT: 3000
      RPC_SECRET: "coltr4n3"
    depends_on:
      - redis
  plaid-webhook-handler:
    build: plaid-webhook-handler
    command: yarn dev
    ports:
      - '3002:3002'
      - '9231:9231'
    volumes:
      - ./plaid-webhook-handler:/user/src/app
      - /user/src/app/node_modules
    environment:
      PORT: 3002
      REDIS_HOST: redis
    depends_on:
      - redis
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_USER: postgres
      POSTGRES_DB: capital-calendar-dev
    ports:
      - '15432:5432'
  redis:
    image: redis
    ports:
      - '6379:6379'
