apiVersion: v1
kind: Service
metadata:
  name: capcal-api-service
  namespace: default
  labels:
    app: capcal
    name: capcal-api-service
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 3000
      name: api
  selector:
    name: capcal-api
